# Python实现聚类算法

在Python上实现聚类算法，可以通过sklearn机器学习框架。   
[sklearn 官方网站](https://scikit-learn.org/stable/)  
[sklearn 中文翻译](https://www.cntofu.com/book/170/docs/22.md)  
其他的机器学习算法都可以在网站查询如何实现  
![常用聚类算法对比](https://scikit-learn.org/stable/_images/sphx_glr_plot_cluster_comparison_001.png)  
<center>常用聚类算法对比

## 1.K-Means实现  
## 2.有效性评价

### 1.1K-Means介绍

K-Means 通常被称为 Lloyd’s algorithm（劳埃德算法）。  
算法有三个步骤。   
·第一步是选择 initial centroids （初始质心），最基本的方法是从 X 数据集中选择k个样本。初始化完成后，K-Means 由两个其他步骤之间的循环组成。  
·第二步将每个样本分配到其 nearest centroid （最近的质心）。  
·第三步通过取分配给每个先前质心的所有样本的平均值来创建新的质心。计算旧的和新的质心之间的差异，并且算法重复这些最后的两个步骤，直到该值小于阈值。换句话说，算法重复这个步骤，直到质心不再显著移动。

### 1.2安装sklearn

cmd 指令 `pip install scikit-learn`  
安装之前需要numpy和scipy库

### 1.3数据导入

采用Pandas库导入数据  
[Pandas.read的详细介绍](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html)

In [35]:
import pandas as pd

In [36]:
custom_heards = ['one', 'two', 'three']
datA = pd.read_csv(r'D:\\pythonProject5\\2_Word2vec\\word2vec.csv', header=None, names=custom_heards) #数据集的地址

In [37]:
print(datA)

           one       two     three
0     2.913879  0.186417  0.088487
1     2.768410 -0.278809 -0.056139
2     2.857983  0.038774 -0.043560
3     2.759607 -0.050475 -0.018207
4     2.641688 -0.145216 -0.037949
...        ...       ...       ...
2555 -0.972605  0.003636  0.008240
2556 -0.662906 -0.002655 -0.000952
2557 -0.486462 -0.006435 -0.000859
2558 -0.820738 -0.002231 -0.005592
2559 -0.728428 -0.001643 -0.004654

[2560 rows x 3 columns]


In [38]:
data=datA['one']

In [39]:
print(data)

0       2.913879
1       2.768410
2       2.857983
3       2.759607
4       2.641688
          ...   
2555   -0.972605
2556   -0.662906
2557   -0.486462
2558   -0.820738
2559   -0.728428
Name: one, Length: 2560, dtype: float64


这样的数据K-Means函数是不能进行计算的，我们需要对数据进行处理

In [40]:
import numpy as np

In [41]:
data=np.array(data)
print(data)

[ 2.9138794   2.7684097   2.8579826  ... -0.48646197 -0.8207384
 -0.7284283 ]


In [42]:
data=[[i] for  i in  data]   #数组转换成列表并且进行遍历

In [43]:
print(data)

[[2.9138794], [2.7684097], [2.8579826], [2.759607], [2.6416879], [2.729553], [2.9817905], [2.9224672], [2.797273], [2.8684845], [3.078087], [2.7501242], [2.9148774], [3.324113], [2.8572495], [3.3686297], [3.035606], [2.783469], [3.1609337], [2.7055318], [3.0758617], [3.0111732], [2.7497625], [2.7908826], [2.8138716], [2.9566824], [3.1705132], [3.069837], [2.7595887], [3.3214161], [3.211254], [3.138397], [3.1204507], [3.062659], [3.2493005], [3.463263], [2.5762606], [3.1958454], [2.7922843], [2.3488462], [2.793288], [3.0256016], [2.7696378], [3.173705], [3.1008213], [3.1285348], [3.284869], [2.7213798], [3.1164205], [2.9884121], [2.9226904], [2.5562615], [2.6912868], [2.6490037], [3.3610494], [2.5456367], [3.1506371], [2.5369225], [2.5008206], [2.5532708], [2.610327], [2.818743], [2.7692451], [2.2585833], [2.7761984], [3.2197337], [2.425347], [2.4502115], [2.9358356], [1.9974412], [2.8108196], [2.638347], [2.9965806], [2.480291], [3.0024295], [2.784491], [2.8796854], [3.0211544], [2.966

### 1.4K-Means聚类

In [44]:
from sklearn.cluster import KMeans

In [45]:
julei=KMeans(n_clusters=4) #进行kmeans聚类

In [46]:
julei.fit(data) #对聚类的数据进行聚类

d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=10.
  warnings.warn(


KMeans(n_clusters=4)

In [47]:
label=julei.labels_ #获得聚类标签

In [48]:
center=julei.cluster_centers_ #聚类中心

In [49]:
print(center)
print(label)

[[-0.59338754]
 [ 1.13486967]
 [ 0.06099147]
 [ 2.5212897 ]]
[3 3 3 ... 0 0 0]


###  1.5二维聚类

In [23]:
data1=datA['one']
data1=np.array(data1)

[2.9138794, 2.7684097, 2.8579826, 2.759607, 2.6416879, 2.729553, 2.9817905, 2.9224672, 2.797273, 2.8684845, 3.078087, 2.7501242, 2.9148774, 3.324113, 2.8572495, 3.3686297, 3.035606, 2.783469, 3.1609337, 2.7055318, 3.0758617, 3.0111732, 2.7497625, 2.7908826, 2.8138716, 2.9566824, 3.1705132, 3.069837, 2.7595887, 3.3214161, 3.211254, 3.138397, 3.1204507, 3.062659, 3.2493005, 3.463263, 2.5762606, 3.1958454, 2.7922843, 2.3488462, 2.793288, 3.0256016, 2.7696378, 3.173705, 3.1008213, 3.1285348, 3.284869, 2.7213798, 3.1164205, 2.9884121, 2.9226904, 2.5562615, 2.6912868, 2.6490037, 3.3610494, 2.5456367, 3.1506371, 2.5369225, 2.5008206, 2.5532708, 2.610327, 2.818743, 2.7692451, 2.2585833, 2.7761984, 3.2197337, 2.425347, 2.4502115, 2.9358356, 1.9974412, 2.8108196, 2.638347, 2.9965806, 2.480291, 3.0024295, 2.784491, 2.8796854, 3.0211544, 2.9661062, 2.7180474, 2.7660723, 2.3207881, 2.7560492, 3.0175617, 2.4862297, 2.5935156, 2.2277575, 2.582632, 2.6855352, 2.5736544, 2.186722, 2.3505678, 2.4074965,

In [22]:
data2=datA['two']
data2=np.array(data2)

In [24]:
DATA2= np.vstack((data1,data2)).T

In [19]:
print(DATA2)

[[ 3.029       8.72423221]
 [ 2.679      10.46206897]
 [ 2.439      11.94505337]
 [ 2.438      12.72278996]
 [ 2.574      12.74494513]
 [ 2.681      12.46396976]
 [ 3.344       8.03041981]
 [ 3.011       9.45043158]
 [ 2.648      10.9858503 ]
 [ 2.45       12.02398714]
 [ 2.522      12.08415681]
 [ 2.684      11.8281408 ]
 [ 3.402       8.04999891]
 [ 3.184       8.63479379]
 [ 2.847       9.48662972]
 [ 2.585      10.11364231]
 [ 2.597      10.20110523]
 [ 2.824      10.02774124]
 [ 3.698       5.94874726]
 [ 3.476       6.39430857]
 [ 3.157       7.37538492]
 [ 2.881       8.07483853]
 [ 2.828       8.4340624 ]
 [ 3.059       8.84187356]]


In [25]:
julei=KMeans(n_clusters=4) #进行kmeans聚类

In [26]:
julei.fit(DATA2) #对聚类的数据进行聚类

d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=10.
  warnings.warn(


KMeans(n_clusters=4)

In [27]:
label=julei.labels_ 
print(label)

[1 1 1 ... 3 3 3]


## 2.有效性评价

### 2.1有效性评价标准

聚类算法属于无监督学习方法，不同的聚类数对聚类结果影响很大。  
所以需要进行聚类有效性评价。  
聚类评价指标比较多，常用的有：Rand指数、轮廓系数（Silhouette Coefficient）、Calinski-Harabaz 指数等等

### 2.2轮廓系数进行聚类评价

轮廓系数处于-1至1，越大表示簇间相似度高而不同簇相似度低，即聚类效果越好。

In [28]:
from sklearn.metrics import silhouette_samples 

In [29]:
lkxs=silhouette_samples(DATA2,label)

In [30]:
print(lkxs)

[0.68650407 0.68541698 0.72057516 ... 0.67600347 0.73039336 0.77889123]


In [31]:
means=np.mean(lkxs)
print(means)

0.5947291311570856


轮廓系数的均值就能表示不同聚类数的好坏，因为我们可以写一个循环来计算聚类数从2到n-1的轮廓系数进行聚类评价

In [32]:
def juleipingjia(n):
    julei=KMeans(n_clusters=n)
    julei.fit(DATA2)
    label=julei.labels_
    lkxs=silhouette_samples(DATA2,label,metric='euclidean')
    means=np.mean(lkxs)
    return means

In [33]:
y=[]
for n in range(2,23):
    means=juleipingjia(n)
    y.append(means)

d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=10.
  warnings.warn(
d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=10.
  warnings.warn(
d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=10.
  warnings.warn(
d:\Program Files\anaconda3\envs\word5\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserW

In [34]:
print(y)

[0.7337200361644182, 0.6544971445374324, 0.5948451019239174, 0.5714477996385515, 0.5697044996230338, 0.5339329289068298, 0.5307702596448203, 0.5196535910591408, 0.5206682051616885, 0.5242698974300007, 0.5190604882613644, 0.5168011800604154, 0.5111464885145055, 0.5086442411739084, 0.5042429407182202, 0.5087425782398783, 0.5018053077530205, 0.5053617887570327, 0.5096939686776141, 0.4944440177711183, 0.48897786167504653]


分别计算轮廓系数就能看出最佳聚类数